import { t } from "./brand";

export const appNav = [
  { href: "/dashboard", label: "Accueil", sub: "Vue d'ensemble", icon: "home", step: null },
  { href: "/candidate/recherche", label: "Candidatures IA", sub: "Recherche & offres", icon: "search", step: null },
  { href: "/profile", label: "Mon CV", sub: "Mon CV & profil", icon: "cv", step: 1 },
  { href: "/prospects", label: "Entreprises", sub: "Recherche entreprises", icon: "search", step: 2 },
  { href: "/prospects/panier", label: "Ma Sélection", sub: "Mes entreprises sélectionnées", icon: "cart", step: 3 },
  { href: "/campaigns", label: "Candidatures", sub: "Mes candidatures", icon: "send", step: 4 },
  { href: "/candidate/entretien", label: "Entretien IA", sub: "Simulateur audio", icon: "send", step: null },
  { href: "/credits", label: "Crédits", sub: "Crédits & abonnement", icon: "credits", step: null, highlight: true },
  { href: "/parametres", label: "Paramètres", sub: "", icon: "settings", step: null },
];

export const pricingPage = {
  title: "Passez à la vitesse supérieure",
  subtitle: "Automatisez vos candidatures, multipliez vos opportunités",
  annualBadge: "2 mois offerts",
  guarantee: "Garantie satisfait ou remboursé sous 7 jours",
  freeTrialBanner: "Testez gratuitement : 1000 crédits offerts (~5 candidatures) et l'analyse CV offerte.",
  freeTrialSub: "Accédez immédiatement à la recherche d'entreprises et lancez vos premières candidatures. Dès votre premier achat (pack ou abo) : sélectionnez autant d'entreprises que vous voulez.",
  freeTrialCta: "Profiter de l'essai gratuit",
  testimonialsTitle: t("Ils ont trouvé leur poste avec Jobea"),
  refundText: "Sous 7 jours et si moins de 200 crédits ont été utilisés, vous pouvez demander un remboursement à support@talentloop.fr (1 par compte). Voir les conditions complètes. Packs de crédits non remboursables.",
  stripe: "Paiements sécurisés par Stripe.",
  faqs: [
    { q: "Les crédits expirent-ils ?", a: "Non, vos crédits n'expirent jamais. Vous pouvez les utiliser à votre rythme." },
    { q: "Puis-je annuler à tout moment ?", a: "Oui, sans engagement. Annulez votre abonnement en un clic depuis votre espace." },
    { q: "Et si je ne suis pas satisfait ?", a: "Remboursement possible sous 7 jours si moins de 200 crédits utilisés." },
    { q: "Quelle est la différence entre pack et abonnement ?", a: "L'abonnement recharge vos crédits chaque mois. Les packs sont des recharges ponctuelles sans abonnement." },
  ],
  plans: [
    {
      name: t("Jobea Pro"),
      headline: "Décrochez vos premiers entretiens",
      candidaturesLabel: "~100 candidatures personnalisées par mois",
      badge: "~100 candidatures/mois",
      weekly: "6",
      monthly: "24",
      annualMonthly: "20",
      cta: "Démarrer maintenant",
      variant: "white" as const,
      features: [
        "9 500 crédits TalentLoop rechargés chaque mois",
        "Accès à toutes les fonctionnalités de la plateforme",
        "Accès à tous les résultats de recherche entreprises (plus de limite à 5)",
        "~100 candidatures complètes estimées par mois",
        "Suivi des candidatures et analytics",
        "Support par email",
        "Sans engagement, annulez à tout moment",
      ],
    },
    {
      name: t("Jobea Premium"),
      headline: "La formule complète pour trouver vite",
      candidaturesLabel: "~250 candidatures personnalisées par mois",
      badge: "~250 candidatures/mois",
      weekly: "8,75",
      monthly: "35",
      annualMonthly: "29",
      cta: "Maximiser mes chances",
      tag: "RECOMMANDÉ",
      variant: "gradient" as const,
      features: [
        "23 500 crédits TalentLoop rechargés chaque mois",
        "Accès à toutes les fonctionnalités de la plateforme",
        "Accès à tous les résultats de recherche entreprises (plus de limite à 5)",
        "~250 candidatures complètes estimées par mois",
        "Traitement prioritaire des enrichissements",
        "Support prioritaire et analytics avancés",
        "Export PDF illimité de vos lettres",
        "Sans engagement, annulez à tout moment",
      ],
    },
    {
      name: t("Jobea Intensif"),
      headline: "Campagne intensive, account manager dédié",
      candidaturesLabel: "Plan pour campagne massive avec support VIP 12h et account manager dédié",
      badge: "~500 candidatures/mois",
      weekly: "13,75",
      monthly: "55",
      annualMonthly: "46",
      cta: "Lancer une campagne massive",
      variant: "dark" as const,
      features: [
        "47 000 crédits TalentLoop rechargés chaque mois",
        "Accès à toutes les fonctionnalités de la plateforme",
        "Accès à tous les résultats de recherche entreprises (plus de limite à 5)",
        "~500 candidatures complètes estimées par mois",
        "Support VIP avec réponse sous 12h",
        "Account manager dédié pour optimiser vos campagnes",
        "Traitement prioritaire des enrichissements",
        "Export PDF illimité de vos lettres",
        "Sans engagement, annulez à tout moment",
      ],
    },
  ],
  testimonials: [
    { text: "J'ai trouvé un stage en 3 semaines grâce à DC Start. Les lettres générées sont bluffantes.", author: "Constant", city: "France" },
    { text: "Rapide et efficace. En tant qu'étudiant, ça m'a fait gagner un temps fou pour candidater.", author: "Étudiant", city: "France" },
    { text: "L'analyse CV m'a permis de corriger des erreurs que je faisais depuis des années.", author: "Thomas D.", city: "Lyon" },
  ],
};
